# Generated by Django 5.1.4 on 2025-03-09 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA_forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_flagged',
        ),
        migrations.AddField(
            model_name='question',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, related_name='pinned_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
