# Generated by Django 5.1.4 on 2025-04-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA_forum', '0002_remove_question_is_flagged_question_pinned_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerimage',
            name='image',
        ),
        migrations.AddField(
            model_name='answerimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
