# Generated by Django 5.1.4 on 2025-03-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_feature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='department',
            field=models.CharField(choices=[('COMMON', 'Common (First Year)'), ('CS', 'Computer Science'), ('ME', 'Mechanical Engineering'), ('EE', 'Electrical Engineering')], default='CS', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='subject',
            field=models.CharField(default='DBMS', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='tags',
            field=models.CharField(blank=True, help_text='Enter comma-separated tags (e.g., calculus, integration)', max_length=255),
        ),
    ]
