# Generated by Django 5.1.4 on 2025-04-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_feature', '0002_notes_department_notes_semester_notes_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
