# Generated by Django 5.1.4 on 2025-04-14 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_feature', '0003_alter_notes_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='description',
        ),
    ]
