# Generated by Django 5.1.4 on 2025-04-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_feature', '0004_remove_notes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='department',
            field=models.CharField(choices=[('HUMANITIES', 'Humanities'), ('COMPUTER', 'Computer Engineering'), ('EXTC', 'Electronics & Telecommunication'), ('ELECTRICAL', 'Electrical Engineering'), ('MECHANICAL', 'Mechanical Engineering')], max_length=50),
        ),
    ]
