# Generated by Django 5.1.4 on 2025-04-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_feature', '0005_alter_notes_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='department',
            field=models.CharField(choices=[('HUMANITIES', 'Humanities'), ('COMPUTER', 'Computer Engineering'), ('IT', 'Information Technology'), ('EXTC', 'Electronics & Telecommunication'), ('ELECTRICAL', 'Electrical Engineering'), ('MECHANICAL', 'Mechanical Engineering')], max_length=50),
        ),
    ]
