# Generated by Django 5.1.4 on 2025-04-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_feature', '0007_notes_description_notes_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='drive_url',
            field=models.URLField(blank=True, help_text='Link to the uploaded file on Google Drive', null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a description of your notes (optional)', null=True),
        ),
    ]
